### ISSUE TITLE
Remember last search

### ISSUE THREAD

**Issue by MightyCreak** [Yggdroot/LeaderF#62]
I often open a file and then need to open the same file name but with .cs or .h or .cpp or .xml, or a slightly different file name, but the beginning of the name is the same.

I think it would be nice if the previous search was still here when hitting `<Leader>F` again.
And since Ctrl-U already work in LeaderF, if I don't need the previous search, I just need to use this shortcut.

Thx!

**Edit:** `<Leader>` was eaten by the markdown formatting, fixed that.

**Comment by Yggdroot** [comment]
Support history just like the shell command line?

**Comment by MightyCreak** [comment]
I was thinking of something even less difficult to implement, it would just show the previous search when hitting LeaderF.

Example: I would type <Leader>F, the search box is empty, I type "myfile", I see "myfile.cpp" and myfile.h" in the results, I select "myfile.h", then I'd type again <Leader>F, and "myfile" would still be here, with "myfile.cpp" and myfile.h" in the results, but this time I'd select "myfile.cpp".

**Comment by Yggdroot** [comment]
If you want this feature, I think it's better to add history support like the shell command line.
I'll add it to the todo list.

**Comment by MightyCreak** [comment]
I actually prefer to show the previous search than having the search history. I don't think I would need to go very deep in the history, most of the time I want to open the files with around the same name.

But both feature aren't exclusive though, we can have history, but also show the previous search when typing `<Leader>F`.

**Comment by Yggdroot** [comment]
Added, Please set `let g:Lf_RememberLastSearch = 1` and have a try.

**Comment by MightyCreak** [comment]
Thanks a lot!

**Comment by MightyCreak** [comment]
Hmmm it doesn't work here (on Mac at least).
When I hit \<Leader\>F again, I do have the previous search written in the bottom line, but I don't have any result, to have them back, I need to delete the last character and re-write it again, then the results are shown.

**Comment by Yggdroot** [comment]
Can not reproduce on my Mac.

**Comment by MightyCreak** [comment]
Same version as well.
It's a bit weirder actually... Sometime I do have results the second time I hit \<Leader\>F, but I have only a portion of it. For instance I searched for a file, I got 34 results out of 52417**, I choose my file, then I hit \<Leader\>F again and I only have 1 result now.

**: This number of files could be divided by two if I was able to set my own ignore dirs/files patterns on top of the .hgignore of my project, that's why this feature would also help me a lot

**Comment by MightyCreak** [comment]
Oh wow, it might actually not be linked to this feature actually. It seems to be bigger :/
If I write my search I get the 34 results and simply if I hit backspace, I get only 1 result, which is impossible, I should have at least 32 results.

**Comment by Yggdroot** [comment]
Fixed. Please use the dev branch to have a try.

**Comment by Yggdroot** [comment]
Fixed, please use the dev branch to have a try.

**Comment by MightyCreak** [comment]
It's not entirely fixed.

It's fixed when searching for a word, selecting a file and hitting \<Leader\>F again (with `let g:Lf_RememberLastSearch = 1`) (first issue)
But it's not fixed when searching for a word and hitting backspace (second issue).

**Comment by MightyCreak** [comment]
It's really easy to have the second issue for me, I enter a word, any one, then hit backspace and I get less results than with a bigger word.

For instance:
* I wrote `tes` and got 15707 results
* I added a `t` (to write `test`) and got 10625 results
* I removed the `t` and got 8026 results (though I expected 15707)

**Comment by Yggdroot** [comment]
I know this issue, it works as designed.
I think you must have set `let g:Lf_CursorBlink = 0`, this option makes LeaderF not asynchronous any more.
In order to get good performance, LeaderF does not search all the files when you input every character, it searches the files progressively.
For example, there are `100,000 `files, you are searching `test`,

1. you type `t`, it searches first `n`(e,g, 10,000) files, then there are 500 files matched.
2. typing `e`, it tries to match `te` from the 500 files and `n - 500` new files out of the left `100,000 - n` files.
3. the same logic for `s`, `t`

So, if you hit backspace, it works as you are searching `tes` from the first `n` files. I would be too slow to search from all the files(`100,000`).
If you have set have set `let g:Lf_CursorBlink = 1`, LeaderF will work asynchronously, it will work as you expected. But for Macvim, there is issue #48 .

**Comment by MightyCreak** [comment]
Yep, you're right, I have `let g:Lf_CursorBlink = 0` because I have Macvim...

But if I follow the algorithm you've described: each time I type a new letter, I search the new pattern in the current result and fetch a new batch of files to search in. And this applies also to the backspace key.
Then, how is it possible that I get fewer result when I hit backspace? In your example, it should take the results from the `test` search, match them with `tes` (which would get the exact same results, because if `test` was found then surely `tes` was there too), then fetch a new batch of files and match them with `tes`.
So even if nothing is found in the newly fetched batch of files, there should be at least the same amount of results.

Am I wrong somewhere in the logic?

**Comment by Yggdroot** [comment]
If you type backspace, the search always start from the beginning.  Assume that there are 10K files, and there are 1000 files match `tes`, and 200 files match `test`, if hit backspace, the result should be 200 or 1000? According to current logic, the result is 1000.
Please install the C extension, follow [here](https://github.com/Yggdroot/LeaderF/blob/master/README.md#performance).
If C extension is installed, LeaderF will match `35,000` files every time.  If there are less than 35,000 files, the issue won't exist any more.
If you want this issue completely fixed, `let g:Lf_CursorBlink = 1`.

**Comment by MightyCreak** [comment]
> If you type backspace, the search always start from the beginning. Assume that there are 10K files, and there are 1000 files match `tes`, and 200 files match `test`, if hit backspace, the result should be 200 or 1000? According to current logic, the result is 1000.

Exactly! but right now I have less than 200 files after typing backspace, which seems illogical.

As I wrote previously:
* `test`: 10625 results
* `tests`: 6952 results
* backspace (`test`): 4373 results
---> less than the first result. isn't it weird?

**Comment by Yggdroot** [comment]
No, as to `test: 10625 results`, it searches 4 times, 

1. `t`, first 30,000 files, `n1` files matched
2. `te`, `n2` files matched in `n1` and  (`30,000` - `n1`) new files, `n2` is the result of 60,000-`n1` files
3. `tes`, `n3` is the result of 30,000+(30,000-n1)+(30,000-n2)=90,000-n1-n2 files
4. `test`, `10625` is the result of 120,000 - n1 - n2 - n3 files

After hitting backspace, it only search `test` in the first `30,000`(nameOnly mode)/`5,000`(fullPath mode) files out of all the files, only search one time. There are `4373` files matched in `30,000`(nameOnly mode)/`5,000`(fullPath mode) files.

**Comment by MightyCreak** [comment]
Right, I understand. Thanks for the detailed explanations!

And I guess you can't match with the current results when hitting backspace, since you might get duplicates with the new fresh search.

I really hope macvim will fix this bug.

I think it would be relevant to add a note in the doc saying that if disabling cursor blink, then you also disable asynchronous search. Because one would think that it's just an aesthetic option, but wouldn't understand why the search behaviour is different.

**Comment by MightyCreak** [comment]
I think there's a bug with the `g:Lf_RememberLastSearch` option, say I open two or more files with \<Leader\>-F. I can't find them in \<Leader\>-B. Even though nothing is in the search bar at the bottom, if I hit Ctrl-U, all the buffers suddenly appear in the list.

**Comment by Yggdroot** [comment]
Can not reproduce on my computer.
1. Are you using the latest LeaderF?
2. Does the issue happen often?
3. What is the exact steps to reproduce it?
